name: "Auto-merge release branch"

on:
  pull_request:
    branches:
      - 'develop'
    paths:
      - 'VERSION'

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Determine version to release
        run: |
          echo "RELEASE_TAG=v$(echo $SOURCE_BRANCH | sed -e 's/release\/v\{0,1\}//')" >> $GITHUB_ENV
        env:
          SOURCE_BRANCH: ${{ github.event.pull_request.head.ref }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Check existence version tag
        run: |
          echo "version: $RELEASE_TAG"
          if [[ "$(git show-ref --tags ${RELEASE_TAG} --quiet)" =~ ${RELEASE_TAG} ]]; then
          echo "Not merging because the release tag ${RELEASE_TAG} already exists"
          exit 1
          fi
      - name: Merge pull request
        run: |
          echo "version: $RELEASE_TAG"
          echo "source: $SOURCE_BRANCH"
          if [[ "$SOURCE_BRANCH" =~ ^release/v?[0-9]+(.[0-9]+){2} ]]; then
          gh pr merge ${{ github.event.pull_request.number }} --squash --delete-branch
          else
          echo "Not merging because the source branch is not a release branch"
          exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SOURCE_BRANCH: ${{ github.event.pull_request.head.ref }}
      - name: Add version tag
        run: |
          git checkout ${{ github.event.pull_request.base.ref }}
          git pull
          git tag ${RELEASE_TAG}
          git push origin ${RELEASE_TAG}
