name: "Auto-merge release"

on:
  pull_request:
    branches:
      - 'release/v[0-9]+.[0-9]+.[0-9]+'
      - 'feature/gh1/github-action-merge-release-branch'
#    paths:
#      - 'VERSION'

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
      - run: echo $PATH
      - run: env
  auto_merge:
    runs-on: ubuntu-latest
    steps:
#      - run: gh pr merge [<number> | <url> | <branch>] [flags]
      - run: |
          echo "Pull Request: ${PRNUM}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRNUM: ${{ github.event.pull_request.number }}

#https://docs.github.com/en/actions/guides/using-github-cli-in-workflows:
#  GITHUB_REF=refs/pull/20/merge