name: "Auto-merge release branch"

on:
  pull_request:
    branches:
      - 'release/v?[0-9]+.[0-9]+.[0-9]+'
      - 'feature/gh1/github-action-merge-release-branch'
#    paths:
#      - 'VERSION'

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Determine and remember version to release
        # Make sure to use a sed substitution that matches the naming of your release branches
        run: |
          echo "NEVER_VERSION=$(echo $PRHEAD | sed -e 's/release\///')" >> $GITHUB_ENV
        env:
          PRHEAD: ${{ github.event.pull_request.head.ref }}
      - uses: actions/checkout@v2
      - name: Merge pull request
        run: |
          gh pr merge $PRNUM --merge
        env:
          PRNUM: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Tag merge commit with new version
        run: |
          git tag "${NEVER_VERSION}" $PRBASE
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRBASE: ${{ github.event.pull_request.base.ref }}