name: "Auto-merge release branch"

on:
  pull_request:
    branches:
      - 'release/v?[0-9]+.[0-9]+.[0-9]+'
      - 'feature/gh1/github-action-merge-release-branch'
#    paths:
#      - 'VERSION'

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Determine and remember version to release
        # Make sure to use a sed substitution that matches the naming of your release branches
        run: |
          echo "RELEASE_VERSION=$(echo $PR_HEAD_REF | sed -e 's/release\/v\{0,1\}//')" >> $GITHUB_ENV
        env:
          PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
      - uses: actions/checkout@v2
      - name: Merge pull request
        run: |
          gh pr merge $PR_NUMBER --merge
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Tag merge commit with new version
        run: |
          git tag "v${RELEASE_VERSION}"
          git push --tags