name: "Auto-merge release"

on:
  pull_request:
    branches:
      - 'release/v[0-9]+.[0-9]+.[0-9]+'
      - 'feature/gh1/github-action-merge-release-branch'
#    paths:
#      - 'VERSION'

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
      - run: echo $PATH
      - run: env
  auto_merge:
    runs-on: ubuntu-latest
    steps:
#      - run: gh pr merge [<number> | <url> | <branch>] [flags]
      - name: Set required environment variables
        run: |
          echo "Pull Request: ${PRNUM}"
          echo "Base: ${PRBASE}"
          echo "Head: ${PRHEAD}"
          echo "Version: `echo $PRHEAD | sed -e 's/release\///'`"
          echo "NEVER_VERSION=$(echo $PRHEAD | sed -e 's/release\///')" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRNUM: ${{ github.event.pull_request.number }}
          PRBASE: ${{ github.event.pull_request.base.ref }}
          PRHEAD: ${{ github.event.pull_request.head.ref }}
      - name: Test one of the env vars
        run: |
          echo "Version: $NEVER_VERSION"
      - uses: actions/checkout@v2
        with:
          ref: $PRHEAD
      - name: Merge
        run: |
          gh pr merge $PRNUM --merge
        env:
          PRHEAD: ${{ github.event.pull_request.head.ref }}
          PRNUM: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#https://docs.github.com/en/actions/guides/using-github-cli-in-workflows:
#  GITHUB_REF=refs/pull/20/merge

# TODO:
# - merge
# - tag